#!/usr/bin/env bash
# Install Nginx on both  servers
# Listen on port 80
# Setup error page, redirection, & return "Hello World" on curl request on port 80
# Add a custom HTTP header - X-Served-By with a value of the hostname of the server

sudo apt-get update
sudo apt-get install -y nginx
mkdir -p /var/www/html
touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
